# Generated by Django 5.2.16 on 2026-08-13 16:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay')], default='razorpay', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net banking'), ('wallet', 'Wallet'), ('emi', 'EMI'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='created', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text="Gateway's bank-facing reference (UTR/ARN/RRN) for this payment, if any.", max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refund_status', models.CharField(choices=[('none', 'No refund'), ('partial', 'Partially refunded'), ('full', 'Fully refunded')], default='none', max_length=10)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Most recent raw gateway payload received for this payment.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cart.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(help_text="e.g. 'created', 'client_verified', 'webhook:payment.captured', 'refund_initiated'.", max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_refund_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processed', 'Processed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Staff member who initiated this refund from the admin, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('return_request', models.ForeignKey(blank=True, help_text='Set when this refund was initiated from a return request, rather than a standalone refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay')], max_length=20)),
                ('dedupe_key', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'dedupe_key'), name='unique_gateway_webhook_event')],
            },
        ),
    ]
