# Generated by Django 5.2.16 on 2026-08-13 16:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. "2025-26".', max_length=9, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeServiceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postal_code', models.CharField(max_length=12, unique=True)),
                ('is_serviceable', models.BooleanField(default=False, help_text='Uncheck to block checkout for this pincode. Rows are only added for exceptions.')),
                ('note', models.CharField(blank=True, help_text='e.g. "Courier doesn\'t reach this area."', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pincode serviceability',
                'ordering': ['postal_code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_state', models.CharField(help_text="Snapshot of the buyer's shipping state, used to decide CGST+SGST vs IGST.", max_length=100)),
                ('seller_state', models.CharField(help_text='Snapshot of COMPANY_STATE at generation time.', max_length=100)),
                ('pdf', models.FileField(upload_to='invoices/%Y/%m/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='cart.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(upload_to='packing_slips/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='packing_slip', to='cart.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('delhivery', 'Delhivery'), ('bluedart', 'Blue Dart'), ('dtdc', 'DTDC'), ('india_post', 'India Post'), ('ekart', 'Ekart'), ('self', 'Self-shipped'), ('other', 'Other')], default='other', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('tracking_url', models.URLField(blank=True, help_text='Paste the tracking link the courier provides for this shipment.')),
                ('status', models.CharField(choices=[('pending', 'Pending assignment'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('ndr', 'Delivery attempt failed'), ('returned', 'Returned to seller'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='cart.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Staff member who triggered this change directly. Blank means system-triggered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='fulfillment.shipment')),
            ],
            options={
                'verbose_name_plural': 'Shipment status history',
                'ordering': ['created_at'],
            },
        ),
    ]
