# Generated by Django 5.2.16 on 2026-08-13 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierImageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_image', models.ImageField(upload_to='picweight/uploads/%Y/%m/')),
                ('cyan_frame_image', models.ImageField(blank=True, upload_to='picweight/processed/%Y/%m/')),
                ('blue_frame_image', models.ImageField(blank=True, upload_to='picweight/processed/%Y/%m/')),
                ('ultra_zoom_image', models.ImageField(blank=True, upload_to='picweight/processed/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(blank=True, help_text='Optionally link this processed photo set to one of your product listings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picweight_jobs', to='catalog.product')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picweight_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
