# Generated by Django 5.2.16 on 2026-08-13 16:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^[0-9]{10}$')])),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark once this enquiry has been followed up.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=150)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Leave blank to fall back to the site logo / initials badge.', upload_to='home/banners/')),
                ('cta_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('cta_url', models.CharField(blank=True, help_text='Where the call-to-action button links, e.g. /catalog/ or a full URL.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. "Under Rs 99"', max_length=50)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Products priced at or below this amount are shown when a buyer clicks this tier.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'max_price'],
            },
        ),
        migrations.CreateModel(
            name='HomeTestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='What Our Customers Say', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manually curated reviews'), ('latest', 'Latest high-rated reviews (site-wide)')], default='latest', max_length=20)),
                ('minimum_rating', models.PositiveSmallIntegerField(default=4, help_text="Only used when source is 'Latest' — reviews below this star rating are excluded.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('limit', models.PositiveSmallIntegerField(default=8, help_text='Maximum number of testimonials to show in this section.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manually curated products'), ('latest', 'Latest products (site-wide)'), ('department', 'Latest products from a department')], default='latest', max_length=20)),
                ('limit', models.PositiveSmallIntegerField(default=8, help_text='Maximum number of products to show in this section.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, help_text="Required when source is 'Latest products from a department'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='pages.homesection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('section', 'product')},
            },
        ),
        migrations.CreateModel(
            name='HomeTestimonialSectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.review')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_reviews', to='pages.hometestimonialsection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('section', 'review')},
            },
        ),
    ]
