# Generated by Django 5.2.16 on 2026-08-15 08:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_default_home_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategorySpotlightSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Shop Categories', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active instance (by display order) is shown on the homepage — use this to stage a new version before cutting over, without deleting the old one.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeGallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Behind the AVR', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('instagram_url', models.CharField(blank=True, help_text="Link for the 'Follow Our Journey' button.", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active instance (by display order) is shown on the homepage — use this to stage a new version before cutting over, without deleting the old one.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeLifestyleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Shop Your Look', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active instance (by display order) is shown on the homepage — use this to stage a new version before cutting over, without deleting the old one.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeLovedBySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Loved by Our Customers', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('rating_value', models.DecimalField(decimal_places=1, default=Decimal('4.8'), help_text='e.g. 4.8 — shown as "4.8/5".', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('rating_count_label', models.CharField(blank=True, default='500+ Happy Customers', help_text='e.g. "500+ Happy Customers"', max_length=60)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active instance (by display order) is shown on the homepage — use this to stage a new version before cutting over, without deleting the old one.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=150)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('bullet_1', models.CharField(blank=True, max_length=120)),
                ('bullet_2', models.CharField(blank=True, max_length=120)),
                ('bullet_3', models.CharField(blank=True, help_text='Leave any bullet blank to show fewer than three.', max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='home/promo/')),
                ('cta_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active instance (by display order) is shown on the homepage — use this to stage a new version before cutting over, without deleting the old one.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeTrustStripSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active instance (by display order) is shown on the homepage — use this to stage a new version before cutting over, without deleting the old one.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeValuePropSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Why AVR Collections', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active instance (by display order) is shown on the homepage — use this to stage a new version before cutting over, without deleting the old one.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='homebanner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero (top of homepage)'), ('closing', 'Closing CTA (above footer)')], default='hero', max_length=20),
        ),
        migrations.CreateModel(
            name='HomeCategorySpotlightTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='home/category_spotlight/')),
                ('label', models.CharField(help_text='e.g. "Earrings"', max_length=60)),
                ('tagline', models.CharField(blank=True, help_text='e.g. "Discover your next favourite pair"', max_length=120)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='pages.homecategoryspotlightsection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='home/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('link_url', models.CharField(blank=True, help_text='Optional — e.g. a link to the Instagram post/reel for this item.', max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.homegallerysection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeLifestyleTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='home/lifestyle/')),
                ('label', models.CharField(help_text='e.g. "For Everyday"', max_length=60)),
                ('cta_text', models.CharField(blank=True, default='Shop Now', max_length=30)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='pages.homelifestylesection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeLovedByQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_text', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='pages.homelovedbysection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeTrustStripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield-check', 'Shield (quality / guarantee)'), ('lock', 'Lock (secure payments)'), ('return-arrow', 'Return arrow (easy returns)'), ('truck', 'Truck (fast shipping)'), ('gem', 'Gem (certified / hallmark)'), ('heart', 'Heart (handcrafted / loved)'), ('sparkle', 'Sparkle (premium / quality)'), ('tag', 'Price tag (affordable / value)'), ('headset', 'Headset (support)'), ('medal', 'Medal (guarantee / trust)')], default='shield-check', max_length=30)),
                ('label', models.CharField(help_text='e.g. "Quality Checked"', max_length=60)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.hometruststripsection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeValuePropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield-check', 'Shield (quality / guarantee)'), ('lock', 'Lock (secure payments)'), ('return-arrow', 'Return arrow (easy returns)'), ('truck', 'Truck (fast shipping)'), ('gem', 'Gem (certified / hallmark)'), ('heart', 'Heart (handcrafted / loved)'), ('sparkle', 'Sparkle (premium / quality)'), ('tag', 'Price tag (affordable / value)'), ('headset', 'Headset (support)'), ('medal', 'Medal (guarantee / trust)')], default='gem', max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.homevaluepropsection')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
