# Generated by Django 5.2.16 on 2026-08-13 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('refund_initiated', 'Refund initiated'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('defective', 'Item is defective/damaged'), ('wrong_item', 'Received the wrong item'), ('not_as_described', 'Not as described'), ('no_longer_needed', 'No longer needed'), ('other', 'Other')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text="The buyer's own description of the issue.")),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes — e.g. why a request was rejected.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='cart.order')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who approved/rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('restocked', models.BooleanField(default=False)),
                ('condition_note', models.CharField(blank=True, help_text='Why an item wasn\'t restocked, e.g. "damaged in transit".', max_length=255)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_request_lines', to='cart.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('delhivery', 'Delhivery'), ('bluedart', 'Blue Dart'), ('dtdc', 'DTDC'), ('india_post', 'India Post'), ('ekart', 'Ekart'), ('self', 'Self-shipped'), ('other', 'Other')], default='self', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('awaiting_dispatch', 'Awaiting dispatch'), ('shipped', 'Shipped'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('lost', 'Lost')], default='awaiting_dispatch', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_shipment', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
