# Generated by Django 5.2.16 on 2026-08-13 16:16

import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(help_text='Unique stock keeping unit for tracking.', max_length=64, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price. Must be lower than the regular price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Folded into the displayed price per unit — never shown to buyers as a separate line item.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Folded into the displayed price per unit — never shown to buyers as a separate line item.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="What this product actually costs to buy in, per unit (COGS) — never shown to buyers. Used only for the profitability report (Store Dashboard). Left at 0 for products this hasn't been entered for yet, which the report shows separately rather than treating as free.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_count', models.PositiveIntegerField(default=0, help_text='Total units physically on hand.')),
                ('reserved_count', models.PositiveIntegerField(default=0, help_text='Units held for in-flight checkouts (payment not yet captured). Not directly editable — see inventory.services.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Stock at or below this number is flagged as low in the admin.')),
                ('hsn_code', models.CharField(blank=True, help_text='GST HSN/SAC code for this product, printed on invoices. Leave blank if not yet classified.', max_length=8, verbose_name='HSN code')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Total GST percentage bundled into this product's price (e.g. 5 for 5%). Invoices split this into CGST+SGST or IGST depending on the buyer's state.", max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('28.00'))], verbose_name='GST rate (%)')),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page <title> / social share title for this product. Falls back to the product title if left blank.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text="Overrides the search-result and social share description for this product. Falls back to the product description if left blank — set this explicitly if the description isn't suitable for search snippets (e.g. informal or non-English copy).", max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated search keywords for this product. Falls back to the site default if left blank.', max_length=255)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, help_text='Weighted full-text index (title/keywords/description), kept in sync by catalog.signals. Not user-editable.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(help_text='Unique stock keeping unit for this variant.', max_length=64, unique=True, verbose_name='SKU')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Option values for this variant, e.g. {"Size": "M", "Color": "Red"}.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the base product's price.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the base product's discount price.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_count', models.PositiveIntegerField(default=0, help_text='Total units physically on hand.')),
                ('reserved_count', models.PositiveIntegerField(default=0, help_text='Units held for in-flight checkouts (payment not yet captured). Not directly editable — see inventory.services.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Stock at or below this number is flagged as low in the admin.')),
                ('thumbnail', models.ImageField(blank=True, help_text="Leave blank to use the base product's thumbnail.", upload_to='products/variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Automatically set when the reviewer has a confirmed order for this product.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Set automatically once a back-in-stock email has been sent.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, help_text="Shown on the homepage's Shop by Category section. Leave blank to fall back to a generated initial badge.", upload_to='catalog/subcategory_icons/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.department')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
