# Generated by Django 5.2.16 on 2026-08-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, help_text="Shown on the homepage's Shop by Category section. Leave blank for a generated initial badge.", upload_to='catalog/subcategory_icons/'),
        ),
    ]
